[package]
name = "monthly_budget"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
csv = "1.1.6"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
